[package]
name = "el-dorado"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "el-dorado"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.126"
serde_json = "1.0.64"
tokio = { version = "1", features = ["full"] }
