primary_db:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "eldorado"
secondary_db:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "eldorado"