ed_db:
  require_ssl: false
ftx_db:
  require_ssl: false
gdax_db:
  require_ssl: false
archive_db:
  require_ssl: false
application:
  exchange: "ftx"
  market: "SOL-PERP"
  droplet: "localdev"
  instance_type: "mita"
  archive_path: "../ed"