ed_db:
  require_ssl: false
ftx_db:
  require_ssl: false
gdax_db:
  require_ssl: false
application:
  exchange: "gdax"
  market: "BTC/USD"
  droplet: "localdev"
  ip_addr: "127.0.0.1"
  archive_path: "../ed"